### ISSUE TITLE
Canonical doesn't seems to work ?

### ISSUE THREAD

**Issue by kiuKisas** [artiebits/svelte-seo#14]
```svelte
<SvelteSeo title='test' canonical='https://test.fr' />
```

The following example add the title but doesn't add the canonical link, did I miss something ? Thank's

**Comment by artiebits** [comment]
thank you for reporting the issue, i will take a look

**Comment by biah** [comment]
I just made a pull request  to fix the issue

**Comment by artiebits** [comment]
thank you for the fix, i will write tests and release a new version, hopefully today

**Comment by artiebits** [comment]
i have published a new version `1.2.1` with the fix, let me know if it works
