### ISSUE TITLE
Include `<slot/>` between `<svelte:head>` tags

### ISSUE THREAD

**Issue by benaltair** [artiebits/svelte-seo#17]
To allow for cleaner markup, `<slot>` could be leveraged allowing for custom meta tags to be added in the component itself.

**Comment by biah** [comment]
Fixed it in a pull request

**Comment by artiebits** [comment]
hi folks, i have a question. should `<slot/>` be between `<svelte:head>` tags like it says in the title of this issue, or after `</svelte:head>` like it's implemented in the pull request? https://github.com/artiebits/svelte-seo/pull/20/files

**Comment by biah** [comment]
Hey👋,
Sorry my bad. I made a mistake😔. It's supposed to be included in the Svelte: head.
I have fixed the problem☺️.

**Comment by artiebits** [comment]
no problem :) thank you for your contribution. i will merge your PR and publish a new version of the package shortly

**Comment by artiebits** [comment]
i've just published the version 1.3.0 which contains requested `<slot>`
