### ISSUE TITLE
Duplicate json-ld schemas

### ISSUE THREAD

**Issue by MyIsaak** [artiebits/svelte-seo#22]
**Describe the bug**
There are 2 JSON+LD script tags instead of 1 in dev and static build using svelte-kit's static adater.

**To Reproduce**
1. Setup skeleton svelte-kit project `npm init svelte@next`
2. Replace `/src/routes/index.svelte` with the following:
```svelte
<script>
    import SvelteSeo from "svelte-seo";
</script>

<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
<SvelteSeo jsonLd={{
    '@context': 'http://www.schema.org',
    '@type': 'Locksmith',
    name: 'BOLT Schlüsseldienst',
    priceRange: '$',
    openingHours: 'Mo,Tu,We,Th,Fr,Sa,Su 00:00-24:00'
}}/>
```
3. Run `npm dev` and open browser and inspect devtools.

**Expected behavior**
Only 1 JSON+LD script tag should be added.

**Screenshots**

![image](https://user-images.githubusercontent.com/4984415/142774491-d809d2d3-20fe-47dd-be11-d09810da65ee.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 95

**Additional remarks**
When disabling javascript, the bug is fixed.

**Comment by artiebits** [comment]
hi @MyIsaak thank you for submitting the issue and providing details, I appreciate it! I will take a look

**Comment by artiebits** [comment]
Hi, I've created a new Svelte app and tried to reproduce the issue as you described, but it works fine for me, there is only one `JSON+LD` tag. And there is an integration test https://github.com/artiebits/svelte-seo/blob/master/cypress/integration/spec.js#L127 that checks that only one `JSON+LD` script tag appears on the page. 
So, I am closing this issue for now.

**Comment by MyIsaak** [comment]
That's strange. Do the tests run after javascript gets executed? Perhaps we are at different svelte versions. I'll double check again if this issue remains.

**Comment by MyIsaak** [comment]
@artiebits I still have this issue, however it's more related to SvelteKit https://github.com/sveltejs/kit/issues/1035
