### ISSUE TITLE
Would it be appropriate to have a warning on <title> character limits?

### ISSUE THREAD

**Issue by Glench** [artiebits/svelte-seo#26]
I've recently learned that for SEO there is usually a sweet spot under 60 characters for title tag lengths. I was wondering if there was a way to implement a compiler warning for this library when `<title>` tag contents are over 60 characters (or under 25 or something).

**Comment by kudadam** [comment]
Well, the idea seems cool

**Comment by artiebits** [comment]
Seems to be a good idea. Would you like to work on it?

**Comment by Glench** [comment]
Me? Unfortunately I don't have the time.

**Comment by kudadam** [comment]
> Seems to be a good idea. Would you like to work on it?

You can assign it to me, will be glad to work on it😊

**Comment by artiebits** [comment]
@kudadam thanks a lot!

**Comment by kudadam** [comment]
Quick question @artiebits , is the warning going to be displayed in some sort of modal to the user or it will be displayed in the console?

**Comment by artiebits** [comment]
@kudadam good question. console would be enough ;)

**Comment by Glench** [comment]
If it's possible, a warning at compile time would be even better!

**Comment by artiebits** [comment]
good one, I agree with @Glench

**Comment by kudadam** [comment]
> If it's possible, a warning at compile time would be even better!

As in when it's being run in `dev` or `build`?

**Comment by Glench** [comment]
Both, since both dev and build require compiling. That appears to be what the current warnings do in SvelteKit. And outside of SvelteKit compile-time warnings would be useful in other frameworks. No idea if it's possible to raise compile-time warnings from a component though.

**Comment by kudadam** [comment]
> Both, since both dev and build require compiling. That appears to be what the current warnings do in SvelteKit. And outside of SvelteKit compile-time warnings would be useful in other frameworks. No idea if it's possible to raise compile-time warnings from a component though.

Am gonna try and see

**Comment by kudadam** [comment]
A fixed has been provided so the isssue can now be closed

**Comment by artiebits** [comment]
i am going to close this issue for now, because I believe it needs more attention and opinions. As it was discussed in #27 what if I have a perfect title for my page but it is 61 characters long? Then this warning would annoy me.

**Comment by kudadam** [comment]
Yeah you are right 😞
