### ISSUE TITLE
Automatically filling OpenGraph and Twitter cards object with data from the title and description tags

### ISSUE THREAD

**Issue by kudadam** [artiebits/svelte-seo#28]
@artiebits , I was suggesting that, the data for the opengraph tags and twitter cards should be taken from the title tags if they are not initially provided, the reason being it that, in most sites, the data used in the title tag is the same used for the OpenGraph and Twitter Cards. Also, it will save time.

**Comment by artiebits** [comment]
I don't see a big advantage of doing it inside of SvelteSEO. And if you want same title and description for Facebook and Twitter you can easily do it like this: 

```javascript
const title = 'My homepage title';
const description = 'My homepage description';

<SvelteSeo
  title={title}
  description={description}
  openGraph={{
    title,
    description
  }}
/>
```

But what if you want to use one description for Twitter, another for Facebook, and third for Google?
