### ISSUE TITLE
Suggesting a complete rewrite of this library

### ISSUE THREAD

**Issue by kudadam** [artiebits/svelte-seo#44]
Hi @artiebits,
I want to suggest that we rewrite this library entirely. The reason for this is the manner in which this library was initially created.
Currently, there are two popular Svelte libraries for SEO: this library and [Svelte Meta Tags](https://github.com/oekazuma/svelte-meta-tags). 
Though this library has more stars, forks and watches than the library, it has more options than this library. The use of if statements make it really painful to create additional tags since you will be writing a lot of `ifs`.

Also, I suggest we move from using rollup to vite. SvelteKit nows makes it very easy to package a library and we are still using the old-school method.

For the testing, we need to move from cypress to vitest. That's because Vitest is very fast and Cypress takes a very long time to install.

If you would allow, we can outline the goals for the rewrite and I will task myself to coding it.

Thank you

**Comment by artiebits** [comment]
hi @kudadam,

I like your initiative. Feel free to work on these improvements and open PRs, I would appreciate it a lot. My only suggestion is to keep PRs as small as possible (meaning don't do everything in one PR). Let know if you have questions.

**Comment by kudadam** [comment]
@artiebits ,
What am suggesting is that you allow me to start the new rewrite on another branch then I work on it gradually till it's ready.
Here are some of the changes I wanted to make:
  * We will use SvelteKit for the creation of the component. 
  The reason is that, SvelteKit makes it really easy to create libraries with it's `SvelteKit package` command.
  Using it plus Vite is going to be better than using rollup because Svelte no longer uses it.
  Also, it will reduce the amount of code we will write compared to using Rollup.
  
* Instead of using Cypress for the testing, I recommend we use Playwright. 
  This package comes preinstalled with SvelteKit when you are starting a new project and if I am to compare 
  playwright tests to the tests using Cypress, I can write all the test inside a single file which much less code.
  
  Actually, the aim of this whole re-write is to make developing the library easy whiles supporting various features.
  As you can check this library is the most popular Svelte library for handling SEO but it still lacks many important features whiles the others which are not that popular, have much features than this.
  The earlier we start the better.
  
  If you are okay with the changes, you can give me the go ahead and I will start right away.

**Comment by artiebits** [comment]
sure, go ahead 👍 and thanks for your contribution!

**Comment by kudadam** [comment]
Okay, I will start right away
