### ISSUE TITLE
Argument of type 'typeof SvelteSeo' is not assignable to parameter of type ConstructorOfATypedSvelteComponent ......

### ISSUE THREAD

**Issue by woss** [artiebits/svelte-seo#49]
After following the installation from the readme.md i get this error. 

Svelte version:  `"svelte": "3.54.0",`
Kit: `"@sveltejs/kit": "1.0.1",`
SvelteSeo: `"svelte-seo": "1.4.1",`

Import: 

```js
import SvelteSeo from 'svelte-seo';
```

<img width="678" alt="image" src="https://user-images.githubusercontent.com/80440/213747982-1000a7ad-cb79-40cf-9a1a-2ea8d62808f0.png">

**Comment by kudadam** [comment]
This is a typescript issue

**Comment by woss** [comment]
cool, any suggestion how to fix it @kudadam ?

**Comment by kudadam** [comment]
@woss , I'm not able to reproduce the issue, do you mind sending me your repo so I can take a look at it

**Comment by woss** [comment]
the funny thing is that i cannot repro this anymore. :( 

it has been bothering me for 4 days and now just gone 🤔

I'm closing this, and will reopen if it happens again
