### ISSUE TITLE
User Provided LD+JSON assigned to a `data` property in a wrapper object

### ISSUE THREAD

**Issue by mabentley85** [artiebits/svelte-seo#69]
**Describe the bug**
The user provided `jsonLd` object has a wrapper object that looks like this:
```json
{
  "@context": "https://schema.org",
  "data": {
    __USER_PROVIDED_DATA__
  }
}
```
Example:
```json
{
  "@context": "https://schema.org",
  "data": {
    "@context": "https://schema.org",
    "@type": "Blog",
    "@id": "https://www.myblog.com",
    "name": "My Blog",
    "description": "This is my blog's description",
    "url": "https://www.myblog.com",
  }
}
```
When validating the LD+JSON the root object is missing a `@type` property and results in an "Unspecified Type" error

**To Reproduce**
Provide any data for the `jsonLd` component property like this:
```svelte
<SvelteSeo
  title="My Blog"
  description="This is my blog"
  canonical="https://www.myblog.com"
  jsonLd={{
    "@context": "https://schema.org",
    "@type": "Blog",
    "@id": "https://www.myblog.com",
    "name": "My Blog",
    "description": "This is my blog's description",
    "url": "https://www.myblog.com",
  }} />
```

This wrapper is added here:
https://github.com/artiebits/svelte-seo/blob/8c28fcf9d47b33ad2c0723cf7b1bc8b00559d7b0/src/lib/index.svelte#L145-L147

**Expected behavior**
The LD+JSON should be exactly what users provided without the wrapper:
```html
<script type="application/ld+json">
{
    "@context": "https://schema.org",
    "@type": "Blog",
    "@id": "https://www.myblog.com",
    "name": "My Blog",
    "description": "This is my blog's description",
    "url": "https://www.myblog.com",
  }
</script>
```

Or is there a reason for doing it this way?

Thanks!

**Comment by lubiah** [comment]
Hello @mabentley85 ,
It seems what you are saying it's right. It's a typo error.
The "context" being declared isn't a mistake. The data provided by the user is supposed to be merged together without the data object.

This should be the right code
```diff
+ JSON.stringify({ "@context": "https://schema.org", ...data }) + "<" 
- JSON.stringify({ "@context": "https://schema.org", data }) + "<" 
```

I'll open a pull request right away to fix this
