### ISSUE TITLE
Layout wont get overwritten by Page, but appends. 

### ISSUE THREAD

**Issue by ohbob** [artiebits/svelte-seo#78]
**Describe the bug**
Layout seo data doesn't get overwritten by page. It stacks on top, but on e.g facebook, we see the the data from layout, not the page.

**To Reproduce**

1. Add sample SEO data in layout.
2. Add sample SEO data in page.
3. See the contents of page,
4. See error -  data from layout hasn't been overwritten by page.

**Expected behavior**
I would expect that the layout gets overwritten by page Seo Data.

**Additional context**
If this is the intended way, then explain on how you imagine to use the plugin?

**Comment by lubiah** [comment]
Even though the data from the page is appended, when the browser is loading the page, it only takes into account the last tags so it would use those of the page instead of the layout

**Comment by ohbob** [comment]
try facebook and twitter preview and you will see that its not the case, one of them handles them right, the other doesn't

**Comment by lubiah** [comment]
Then inside the layout, try getting the page data from there

**Comment by ohbob** [comment]
> Then inside the layout, try getting the page data from there

I'm not really following on how i can do that. An example would be appreciated.

**Comment by lubiah** [comment]
Sorry, I'm kinda busy but try this.

Return the SEO data from a load function inside the page.

Then inside layout,
Try to access it like this
```svelte
<script>
  import { page } from '$app/stores';
  import Head from 'svelte-seo'
</script>
<Head  facebook={{$page.data.seo.facebook}}/>

```

**Comment by lubiah** [comment]
I'm yet to look into this issue
