### ISSUE TITLE
Ts Types not working with vs code

### ISSUE THREAD

**Issue by anasmohammed361** [artiebits/svelte-seo#82]
**Describe the bug**
Types are not properly exported for svetelkit-v2 project

**To Reproduce**
Create a new sveltekit app , and install the svelte-seo package

**Expected behavior**
Proper Assignment of types

**Comment by MahmoodKhalil57** [comment]
Hey please merge that fix

**Comment by MahmoodKhalil57** [comment]
thank you gods of opensource!
